apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nestjs
  template:
    metadata:
      labels:
        app: hello-nestjs
    spec:
      containers:
      - name: hello-nestjs-container
        image: hello-nestjs-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000